services:
  mongo-wallet:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongdb-wallet-volume:/data/db
    restart: always
    networks:
      - backend

  api:
    container_name: api-wallet
    build: ./api
    restart: always
    ports:
      - "5002:5002"
    depends_on:
      - mongo-wallet
    env_file:
      - ./api/.env 
    networks:
      - backend
  
  nginx:
    container_name: nginx-wallet
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - api
    networks:
      - backend

  spa:
    container_name: spa-wallet
    build:
      context: ./spa
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - spa
    

volumes:
  mongdb-wallet-volume:
networks:
  backend:
  spa: 
